# Use OpenJDK 11 as base image
FROM openjdk:17

# Set working directory
WORKDIR /app

# Copy the JAR file into the container
# COPY target/your-application.jar app.jar
COPY server/build/libs/api-0.0.1-SNAPSHOT.jar app.jar
# Expose port 8080
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]
