# Use node image as base
FROM node:18.18.2

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY client/package.json .

# Copy the rest of the application code
COPY client .

RUN npm install

# Command to start the development server
CMD ["npm", "run", "dev", "--", "--host"]
